/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithms;

import org.junit.jupiter.api.Test;

public class AlgorithmsTest {
    @Test
    public void testSomeLibraryMethod() {
        Algorithms classUnderTest = new Algorithms();
    }
}
