/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithms;

import algorithms.sorting.ISortingAlgorithm;
import algorithms.sorting.InsertionSort;
import algorithms.sorting.Util;

public class Algorithms {
    public static void main(String[] args) {      
    	Integer[] arrayToSort = new Integer[] { 31, 41, 59, 26, 41, 58 };
        ISortingAlgorithm<Integer> insertionSort = new InsertionSort();
        insertionSort.sort(arrayToSort);
        
        Util.printArray(arrayToSort);
    }
}
